name: fetch website and commit results

on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # checkout repo to actions runner
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: execute py script
        run: |
          python main.py --loaddata
