name: fetch website and commit results

on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # checkout repo to actions runner
      - name: checkout repo content
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: setup python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: execute py script
        run: |
          python main.py --loaddata
